apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-test-app
  template:
    metadata:
      labels:
        app: kube-test-app
    spec:
      containers:
      - name: kube-test
        image: kube_test
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: kube-test-service
spec:
  type: NodePort
  selector:
    app: kube-test-app
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8000