zeit.de:
  base_url: http://www.zeit.de/
  crawl_url: http://www.zeit.de/news/index?date=
  timezone: Europe/Berlin
  # TODO parameterize these
  project: scraper-test-307018
  dataset: scraperdata
  table: data
